eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: orderdb
      repositories:
        enabled: true
